=== a7madMa/HTML_Clase/Tema2/hoja2/Ejer06.dtd
<!ELEMENT empleados (empleado*)>
<!ELEMENT empleado (nombre)>
<!ATTLIST empleado codigo ID #REQUIRED>
<!ATTLIST empleado jefe IDREF "e0001">
<!ELEMENT nombre (#PCDATA)>

=== a7madMa/HTML_Clase/Tema2/hoja2/Ejer07.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE empleados SYSTEM "Ejer06.dtd">

<empleados>
<empleado codigo="e0001">
<nombre>Alan Sugar</nombre>
</empleado>
<empleado codigo="e0002" jefe="e0001">
<nombre>Jose Luis Domínguez</nombre>
</empleado>
<empleado codigo="e0003" jefe="e0002">
<nombre>Pedro Ruiz</nombre>
</empleado>
<empleado codigo="e0004" jefe="e0002">
<nombre>Paco Suárez</nombre>
</empleado>
<empleado codigo="e0005" jefe="e0002">
<nombre>Paco Menéndez</nombre>
</empleado>
</empleados>
