=== a7madMa/HTML_Clase/Tema3/ciudad/ciudad.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="ciutat">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nom"/>
            <xs:element ref="state"/>
            <xs:element ref="description"/>
            <xs:element ref="population"/>
            <xs:element ref="location"/>
            <xs:element ref="latitude"/>
            <xs:element ref="longitude"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="nom" type="xs:string"/>

<xs:element name="state">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2}"/>
            <!-- xs:restriction base="xs:string"
             xs:length value="2"-->
        </xs:restriction>
    </xs:simpleType>
    </xs:element>

<xs:element name="description" type="xs:string"/>

<xs:element name="population" type="xs:positiveInteger"/>

<xs:element name="location" type="xs:string"/>

<xs:element name="latitude" type="xs:string"/>

<xs:element name="longitude" type="xs:string"/>





</xs:schema>

=== a7madMa/HTML_Clase/Tema3/ciudad/ciudad.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciutat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ciudad.xsd">
    <nom>Athens</nom>
    <state>GA</state>
    <description> Home of the University of Georgia</description>
    <population>100000</population>
    <location>Located about 60 miles Northeast of Atlanta</location>
    <latitude>33 57' 39" N</latitude>
    <longitude>83 22' 42" W</longitude>
</ciutat>
