=== a7madMa/HTML_Clase/ejemplo_tipos_definidos_usuario/ejemplo_recetas/receta.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="receta">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="medicamento" maxOccurs="10" type="xs:string" />

                <xs:element name="farmacia" type="xs:string" fixed="Farmacia Juaneda" />

                <xs:element name="edad" type="TipoEdad" />


                <xs:element name="nombre" type="TipoNombre" />


                <xs:element name="pago" type="TipoPago" />


                <xs:element name="dni" type="TipoDni" />


                <!-- Un elemento con contenido string y un atributo
                se describe como una extensión de string añadiéndole un
                atributo numColegiado. -->
                <xs:element name="medico" type="TipoMedico" />

                <xs:element name="posologia" type="TipoPosologia" />

                <xs:element name="alergias">
                    <xs:complexType />
                </xs:element>

                <xs:element name="grupo_sanguineo" type="TipoSangre" />


                <xs:element name="instrucciones">
                    <xs:complexType mixed="true">
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="b"></xs:element>
                        </xs:choice>

                    </xs:complexType>

                </xs:element>

            </xs:sequence>

        </xs:complexType>
    </xs:element>

    <!-- Tipos definios por nosotros -->
    <xs:simpleType name="TipoEdad">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="150" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoNombre">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="100" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoPago">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Gratuito" />
            <xs:enumeration value="Íntegro" />
            <xs:enumeration value="Copago" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoDni">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TipoMedico">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="numColegiado" type="xs:integer" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="TipoPosologia">
        <xs:sequence>
            <xs:element name="tomas" type="xs:positiveInteger" />
            <xs:element name="horario" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="duracion" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="TipoSangre">
        <xs:attribute name="tipo" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>


</xs:schema>

=== a7madMa/HTML_Clase/ejemplo_tipos_definidos_usuario/ejemplo_recetas/receta.xml
<?xml version="1.0" encoding="UTF-8"?>

<receta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="receta.xsd">

    <medicamento>Paracetamol</medicamento>
    <medicamento>Omeprazol</medicamento>

    <farmacia>Farmacia Juaneda</farmacia>

    <edad>70</edad>

    <nombre>Francisco Santos</nombre>

    <pago>Gratuito</pago>

    <dni>22119029H</dni>

    <medico numColegiado="171612713">Juan Ríos</medico>

    <posologia duracion="Cinco días">
        <tomas>3</tomas>
        <horario>Mañana, tarde y noche</horario>
    </posologia>

    <alergias />

    <grupo_sanguineo tipo="A+" />

    <instrucciones> Esta medicación debe tomarse en <b>ayunas</b>. No deben superarse los <b>cuatro</b>
        comprimidos al día. </instrucciones>

</receta>
