=== a7madMa/HTML_Clase/ejemplos/ejemplo011.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="autor" type="xs:string" />
                            <xs:element name="nacionalidad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nacional" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="libro">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="isbn" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="autor" type="xs:string" />
                                        <xs:element name="nacionalidad">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="extranjero" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== a7madMa/HTML_Clase/ejemplos/ejemplo01.xml
<?xml version="1.0" encoding="UTF-8"?>

<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejemplo011.xsd">


    <libro>
        <titulo>El Quijote</titulo>
        <autor>Miguel de Cervantes</autor>
        <nacionalidad>
            <nacional />
        </nacionalidad>


        <libro>
            <titulo isbn="120-1212-1212-1212">Estudio en escarlta</titulo>
            <autor>Arthur Conan Doyle</autor>
            <nacionalidad>
                <extranjero />
            </nacionalidad>
        </libro>
    </libro>
</libro>
