=== a7madMa/HTML_Clase/Tema2/Ejemplos/coche.dtd
<!ELEMENT coche (marca,modelo,ocasion?, combustible,extra*)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT ocasion EMPTY>
<!ELEMENT combustible (gasolina|gasoil|electrico|hibrido)>
<!ELEMENT gasolina EMPTY>
<!ELEMENT gasoil EMPTY>
<!ELEMENT electrico EMPTY>
<!ELEMENT hibrido EMPTY>
<!ELEMENT extra (#PCDATA)>

=== a7madMa/HTML_Clase/Tema2/Ejemplos/coche.xml
<?xml version ="1.0" encoding="UTF-8" ?>

<!DOCTYPE coche SYSTEM "coche.dtd">

<coche>
	<marca> Renault</marca>
	<modelo> Clio</modelo>
	<ocasion />
	<combustible>
	<gasolina/>
	</combustible>
	<extra>Asientos calefactados</extra>
	<extra>Elevalunas el√©ctrico</extra>

</coche>
