=== a7madMa/HTML_Clase/Tema2/ejemplos-attlist/coche.dtd
<!ELEMENT taller (coche+, reparacion+)>
<!ELEMENT coche (marca,modelo)>
<!ELEMENT matricula (#PCDATA)>

<!ATTLIST coche fecha_entrada NMTOKEN #IMPLIED>
<!ATTLIST coche fechas_revisiones NMTOKENS #IMPLIED>

<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>

<!ELEMENT reparacion (concepto, precio)>
<!ATTLIST reparacion mat_vehiculo IDREF #REQUIRED>
<!ELEMENT concepto (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT recepcionmat_vehiculo (#PCDATA)>

=== a7madMa/HTML_Clase/Tema2/ejemplos-attlist/coche.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE taller SYSTEM "coche.dtd">

<taller>
	<coche matricula = MAT-7890ECC " fecha_compra="2020-02-01"
		fechas_revisiones="2021-01-25 2022-01-28 2023-02-05">
		<marca>Kia</marca>
		<modelo>Stonic</modelo>
	</coche>
		<coche matricula = MAT-8361DTG "
			fecha_compra="2019-06-10" fechas_revisiones="2020-06-01 2021-06-15">
			<marca>Volkswagen</marca>
			<modelo>Taigo</modelo>
		</coche>
			<reparacionmat_vehiculo = MAT-8361DTG ">
				<concepto>Pinchazo rueda trasera izquiera</concepto>
				<precio>10</precio>
			</reparacion>
</taller>
