=== a7madMa/HTML_Clase/hoja1/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="factura">

        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cliente" />
                <xs:element ref="articulos" />

            </xs:sequence>
            <xs:attribute ref="codigo" use="required" />
            <xs:attribute ref="estado" default="pendiente" />
            <!-- el pendiente del estado es voluntario pero para saber que va ahi-->
        </xs:complexType>
    </xs:element>

    <xs:attribute name="codigo" type="xs:positiveInteger" />
    <xs:attribute name="estado" type="xs:string" />

    <xs:element name="estado">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="pagado" />
                <xs:enumeration value="pendiente" />

            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="cliente">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="nombre">
        <xs:simpleType>
            <xs:restriction>
                <xs:maxLength value="20" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="articulos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="articulo" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="articulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="descripcion" />
                <xs:element ref="precioUnitario" />
                <xs:element ref="unidades" />
            </xs:sequence>
            <xs:attribute ref="iva" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="iva" type="xs:positiveInteger" />

    <xs:element name="descripcion" type="xs:string" />

    <xs:element name="precioUnitario">
        <xs:simpleType>
            <xs:restriction>
                <xs:fractionDigits value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="unidades" type="xs:positiveInteger" />


</xs:schema>

=== a7madMa/HTML_Clase/hoja1/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura codigo="7190" estado="pagado" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="factura.xsd">

    <cliente>
        <nombre>Mariano Pérez</nombre>
    </cliente>
    <articulos>
        <articulo iva="21">
            <descripcion>Pendrive 16GB TDK</descripcion>
            <precioUnitario>9.50</precioUnitario>
            <unidades>
        2</unidades>
        </articulo>
        <articulo iva="16">
            <descripcion>Paquete de 500 folios Ofimarket 80g</descripcion>
            <precioUnitario>6.25</precioUnitario>
            <unidades>
        1</unidades>
        </articulo>
        <articulo iva="16">
            <descripcion>Calculadora Casio científica</descripcion>
            <precioUnitario>12.00</precioUnitario>
            <unidades>
        1</unidades>
        </articulo>
    </articulos>
</factura>
