=== a7madMa/HTML_Clase/hoja1/ofertas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="connexions_ADSL">
        <xs:complexType>

            <xs:sequence>
                <xs:element ref="oferta" maxOccurs="unbounded" />
                <xs:element ref="ofertes_actives" />

            </xs:sequence>

        </xs:complexType>

    </xs:element>
    <xs:element name="oferta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nom" />
                <xs:element ref="nom_companyia" />
                <xs:element ref="velocitat_transferencia" />
                <xs:element ref="preu" />
            </xs:sequence>
            <xs:attribute ref="id" use="required" />
        </xs:complexType>


    </xs:element>
    <xs:attribute name="id" type="xs:positiveInteger" />

    <xs:element name="nom" type="xs:string" />


    <xs:element name="nom_companyia">

        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Arrakis" />
                <xs:enumeration value="Jazztel" />
                <xs:enumeration value="Movistar" />
                <xs:enumeration value="Orange" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="fibra">
        <xs:complexType />
    </xs:element>

    <xs:element name="velocitat_transferencia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pujada" />
                <xs:element ref="baixada" />
            </xs:sequence>
            <xs:attribute ref="unitat" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="unitat">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Kbps" />
                <xs:enumeration value="Mbps" />
                <xs:enumeration value="Gbps" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>


    <xs:element name="pujada" type="xs:decimal" />
    <xs:element name="baixada" type="xs:positiveInteger" />

    <xs:element name="preu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alta" />
                <xs:element ref="linia" />
                <xs:element ref="promocio" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="mensual" />
                <xs:element ref="extres" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="total_mensual" />
            </xs:sequence>
            <xs:attribute ref="moneda" />
        </xs:complexType>
    </xs:element>

    <xs:attribute name="moneda" fixed="Euro">
    </xs:attribute>

    <xs:element name="alta">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="permanencia_alta" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute ref="gratis" use="required"/>
        <xs:attribute ref="permanencia"/>
    </xs:complexType>
    </xs:element>

    <xs:attribute name="gratis">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Si" />
                <xs:enumeration value="No" />
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="permanencia">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Si" />
                <xs:enumeration value="No" />
            </xs:restriction>
        </xs:simpleType>
        </xs:attribute>

    <xs:element name="permanencia_alta"> 
        <xs:complexType>
            <xs:attribute ref="temps" use="required"/>
            <xs:attribute ref="quantitat" use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:attribute name="temps"> 
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="dies"/>
                <xs:enumeration value="mesos"/>
                <xs:enumeration value="anys"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="quantitat">
        <xs:simpleType>
            <xs:restriction base="xs:nonNegativeInteger"/>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="linea">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:fractionDigits value="2"></xs:fractionDigits>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="mensual">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:fractionDigits value="2"></xs:fractionDigits>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="total_mensual" >
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:fractionDigits value="2"></xs:fractionDigits>
            </xs:restriction>
        </xs:simpleType>
        </xs:element>

    <xs:element name="promocio"> 
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="promocio_preu"/>
            </xs:sequence>
            <xs:attribute ref="fins"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="fins" type="xs:date"/>


    <xs:element name="promocio_preu">
        <xs:simpleType>
            <xs:restriction>
                
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="extres" />
    <xs:element name="ofertes_actives" />


</xs:schema>

=== a7madMa/HTML_Clase/hoja1/ofertas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Notes:
L'id de la oferta ha d'esser un enter major d'1.
El nom de la oferta pot anar dins una etiqueta nom.
La velocitat de transferència pot estar en Kbps, Mbps o Gbps
La moneda del preu serà un valor fix Euro.
Els preus tindran dos decimals.
El nom de la companyia serà tret d'una enumeració amb tots els valors possibles
Els atributs els quals valors son si o no sols poden prendre aquests valors
Les dates s'han de verificar en quant a format
La permanència pot esser-hi o no. Si hi és, l'atribut temps pot prendre els valors
dies, mesos i anys.
L'atribut quantitat pot prendre valors sense decimals sencers positius amb el 0 inclòs.
-->
<connexions_ADSL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ofertas.xsd">
    <oferta id="1">
        <nom>Arrakis BT Go</nom>
        <nom_companyia>Arrakis</nom_companyia>
        <velocitat_transferencia
            unitat="Mbps">
            <pujada>20</pujada>
            <baixada>50</baixada>
        </velocitat_transferencia>
        <preu
            moneda="Euro">
            <alta gratis="Si" permanencia="No" />
            <linia>13.97</linia>
            <mensual>36.50</mensual>
            <total_mensual>50.47</total_mensual>
        </preu>
    </oferta>
    <oferta id="2">
        <nom>Arrakis eOficina</nom>
        <nom_companyia>Arrakis</nom_companyia>
        <velocitat_transferencia
            unitat="Mbps">
            <pujada>40</pujada>
            <baixada>120</baixada>
        </velocitat_transferencia>
        <preu
            moneda="Euro">
            <alta gratis="Si" permanencia="No" />
            <linia>13.97</linia>
            <mensual>59.90</mensual>
            <total_mensual>73.87</total_mensual>
        </preu>
    </oferta>
    <oferta id="3">
        <nom>Fibra 300 Megas simétricos + Llamadas gratis con Línea Jazztel </nom>
        <nom_companyia>Jazztel</nom_companyia>
        <fibra />
        <velocitat_transferencia unitat="Mbps">
            <pujada>300</pujada>
            <baixada>300</baixada>
        </velocitat_transferencia>
        <preu
            moneda="Euro">
            <alta gratis="Si" permanencia="No" />
            <linia>0</linia>
            <promocio fins="2019-01-01">
                <promocio_preu>15.94</promocio_preu>
            </promocio>
            <mensual>19.95</mensual>
            <total_mensual>19.95</total_mensual>
        </preu>
    </oferta>
    <oferta id="4">
        <nom>Movistar Fusión fibra 100 Mb</nom>
        <nom_companyia>Movistar</nom_companyia>
        <fibra />
        <velocitat_transferencia
            unitat="Mbps">
            <pujada>50</pujada>
            <baixada>100</baixada>
        </velocitat_transferencia>
        <preu
            moneda="Euro">
            <alta gratis="Si" permanencia="Si">
                <permanencia_alta temps="mesos" quantitat="12" />
            </alta>
            <linia>13.97</linia>
            <promocio
                fins="2019-01-01">
                <promocio_preu>24.90</promocio_preu>
            </promocio>
            <promocio
                fins="2019-06-01">
                <promocio_preu>26.90</promocio_preu>
            </promocio>
            <mensual>29.90</mensual>
            <total_mensual>43.87</total_mensual>
        </preu>
    </oferta>
    <oferta id="5">
        <nom>Movistar Fibra Óptica 300 Mb</nom>
        <nom_companyia>Movistar</nom_companyia>
        <fibra />
        <velocitat_transferencia
            unitat="Mbps">
            <pujada>100</pujada>
            <baixada>300</baixada>
        </velocitat_transferencia>
        <preu
            moneda="Euro">
            <alta gratis="Si" permanencia="Si">
                <permanencia_alta temps="mesos" quantitat="12" />
            </alta>
            <linia>13.97</linia>
            <promocio>
                <promocio_preu>39.90</promocio_preu>
            </promocio>
            <mensual>39.90</mensual>
            <total_mensual>53.87</total_mensual>
        </preu>
    </oferta>
    <oferta id="6">
        <nom>ASDL Rural</nom>
        <nom_companyia>Orange </nom_companyia>
        <velocitat_transferencia
            unitat="Mbps">
            <pujada>0.512</pujada>
            <baixada>6</baixada>
        </velocitat_transferencia>
        <preu
            moneda="Euro">
            <alta gratis="Si" permanencia="Si">
                <permanencia_alta temps="mesos" quantitat="18" />
            </alta>
            <linia>13.97</linia>
            <promocio
                fins="2019-01-01">
                <promocio_preu>11.95</promocio_preu>
            </promocio>
            <mensual>15.95</mensual>
            <total_mensual>29.92</total_mensual>
            <extres>Router Wifi</extres>
            <extres>Alta gratis online</extres>
        </preu>
    </oferta>
    <ofertes_actives>1 4 5 6</ofertes_actives>
</connexions_ADSL>
